modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
    modId="evoked"
    version="${file.jarVersion}"
    displayName="Evoked"
    logoFile="evoked.png"
    credits="DoltHHaven"
    authors="Team Taiga"
    description='''
A mod that spices up Totems by making them more consistent and the process of acquring them more fun
'''
[[dependencies.evoked]]
    modId="forge" 
    mandatory=true 
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evoked]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.evoked]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.4.0,)"
    ordering = "BEFORE"
    side = "BOTH"
